---
version: 4.1.1
title: Potasiepe
description: "Potasiepe: giardiniere a Udine e Gorizia per progettazione giardini, realizzazione giardini, sistemazione giardini, servizi giardinaggio, manutenzione del verde"
url: https://www.potasiepegiardiniere.it
baseurl:
repository: https://github.com/enricocaputo/potasiepe
timezone: Europe/Rome
encoding: UTF-8
lang: it-IT
name: "Potasiepe"

permalink: pretty
collections_dir: my_collections
collections:
  servizi_giardinaggio:
    output: true
    permalink: /servizi-di-giardinaggio/:title/
  posts:
    output: true
    permalink: /consigli-di-giardinaggio/:title/
  calendario:
    output: true
    permalink: /calendario-di-giardinaggio/:title/
  vendita_piante_online:
    output: true
    permalink: /vivaio/:title/

defaults:
  - scope:
      path: "*download"
    values:
      sitemap: false
  - scope:
      path: "_posts"
    values:
      seo:
        type: "Article"
      author: "potasiepe"
      category: "Orto & Giardino"
      comments: "true"
      image: "/img/share-potasiepe.jpg"
  - scope:
      path: "_calendario"
    values:
      author: "potasiepe"
      comments: "false"
      seo:
        type: "Article"

plugins:
  - jekyll-sitemap

paginate: 6
paginate_path: "/consigli-di-giardinaggio/page:num/"
markdown: kramdown

exclude:
  - ".gitignore"
  - CNAME
  - README.md
