---
title: Potasiepe
description: "Potasiepe: giardiniere a Udine e Gorizia per progettazione giardini, realizzazione giardini, sistemazione giardini, servizi giardinaggio, manutenzione del verde"
url: https://www.giardiniere-potasiepe.fvg.it
baseurl:
timezone: Europe/Rome
encoding: UTF-8
lang: it-IT
name: "Potasiepe"
twitter:
  username: potasiepe
  card: summary
social:
  links:
    - https://www.misterimprese.it/friuli-venezia-giulia/udine/cervignano-del-friuli/giardinaggio-servizi/2571124.html
    - https://www.facebook.com/giardiniere.potasiepe/
    - https://twitter.com/potasiepe?lang=it
    - https://www.paginegialle.it/giardinierepotasiepe_baildd
    - https://www.paginebianche.it/cervignano-del-friuli/giardiniere-potasiepe.11997753
    - https://www.yelp.it/biz/potasiepe-cervignano-del-friuli
